const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { Store } = require('../store');
const config = require('../config/gameplay.json');
function make() { return new Store(path.join(fs.mkdtempSync(path.join(os.tmpdir(), 'bhc-')), 'state.json'), config); }
test('crew reservations enforce four-player crews and bind sessions', () => { const s = make(); const c = s.createCrew('a'); s.joinCrew(c.id, 'b'); s.joinCrew(c.id, 'c'); s.joinCrew(c.id, 'd'); assert.throws(() => s.joinCrew(c.id, 'e'), /full/); const r = s.reserve(c.id, 'us-west'); const session = s.bindSession(r.id, 'b'); assert.equal(s.authenticate(session.token).accountId, 'b'); assert.throws(() => s.bindSession(r.id, 'e'), /not in crew/); });
test('lobby reservations cannot exceed 100 players', () => { const s = make(); for (let i = 0; i < 25; i++) { const c = s.createCrew(`p${i}`); for (let j = 1; j < 4; j++) s.joinCrew(c.id, `p${i}-${j}`); s.reserve(c.id, 'us-west'); } const extra = s.createCrew('overflow'); s.joinCrew(extra.id, 'overflow-1'); s.joinCrew(extra.id, 'overflow-2'); s.joinCrew(extra.id, 'overflow-3'); assert.throws(() => s.reserve(extra.id, 'us-west'), /capacity/); });
test('crew vehicle seats and safe reconnect position are authoritative', () => { const s = make(); const c = s.createCrew('driver'); s.joinCrew(c.id, 'passenger'); const v = s.spawnStarterVehicle(c.id, 'driver'); s.boardVehicle(v.id, 'driver'); s.boardVehicle(v.id, 'passenger'); assert.equal(v.occupants.length, 2); s.updateWorldPosition('driver', 'grand_casino'); assert.equal(s.reconnectPosition('driver'), 'grand_casino'); assert.throws(() => s.updateWorldPosition('driver', 'unbuilt_building'), /not playable/); });
test('owner crew is fixed, combat immune, and invite only', () => { const s = make(); const c = s.createCrew('Big Head Developer'); assert.equal(c.id, 'crew_4e5c775890ba'); assert.equal(c.combatImmune, true); assert.throws(() => s.joinCrew(c.id, 'uninvited'), /invite-only/); const invite = s.inviteToCrew(c.id, 'Big Head Developer'); assert.equal(s.joinCrew(c.id, 'invited', invite.inviteToken).members.length, 2); assert.equal(s.createCrew('Big Head Developer').id, c.id); });
test('restaurant order reserves credits and transitions idempotently', () => { const s = make(); const crew = s.createCrew('diner'); s.reserveRestaurantTable('BHC_REST_63RD_CHOPHOUSE', 'Table_03', crew.id, 4); const order = s.createRestaurantOrder({ orderKey: 'order-1', restaurantId: 'BHC_REST_63RD_CHOPHOUSE', tableId: 'Table_03', crewId: crew.id, playerId: 'diner', items: [{ name: '63rd Street Sirloin', quantity: 1 }, { name: 'House Lemonade', quantity: 1 }] }); assert.equal(order.total, 72); assert.equal(s.account('diner').credits, 428); assert.equal(s.createRestaurantOrder({ orderKey: 'order-1', restaurantId: 'BHC_REST_63RD_CHOPHOUSE', tableId: 'Table_03', crewId: crew.id, playerId: 'diner', items: [{ name: '63rd Street Sirloin' }] }).id, order.id); s.transitionRestaurantOrder(order.id, 'preparing'); s.transitionRestaurantOrder(order.id, 'plated'); s.transitionRestaurantOrder(order.id, 'served'); assert.equal(s.account('diner').reservedCredits, 0); assert.throws(() => s.transitionRestaurantOrder(order.id, 'accepted'), /invalid order transition/); });
