const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');

function id(prefix) { return `${prefix}_${crypto.randomBytes(8).toString('hex')}`; }

class Store {
  constructor(file, config) {
    this.file = file;
    this.config = config;
    fs.mkdirSync(path.dirname(file), { recursive: true });
    this.restaurants = JSON.parse(fs.readFileSync(path.join(__dirname, 'config/restaurants.json'), 'utf8'));
    this.state = fs.existsSync(file) ? JSON.parse(fs.readFileSync(file, 'utf8')) : { accounts: {}, crews: {}, lobbies: {}, reservations: {}, sessions: {}, vehicles: {}, worldProgress: {}, restaurantTables: {}, restaurantOrders: {}, audit: [] };
  }
  save() { const tmp = `${this.file}.tmp`; fs.writeFileSync(tmp, JSON.stringify(this.state, null, 2)); fs.renameSync(tmp, this.file); }
  account(accountId) { if (!accountId || typeof accountId !== 'string' || accountId.length > 80) throw new Error('invalid accountId'); if (!this.state.accounts[accountId]) this.state.accounts[accountId] = { id: accountId, createdAt: new Date().toISOString(), credits: 500, reservedCredits: 0 }; return this.state.accounts[accountId]; }
  createCrew(accountId) { this.account(accountId); const owner = this.config.ownerCrew; if (accountId === owner.ownerAccountId) { const existing = this.state.crews[owner.crewId]; if (existing) return existing; const crew = { id: owner.crewId, leaderId: accountId, members: [accountId], ready: {}, combatImmune: true, joinPolicy: 'invite-only', inviteToken: id('invite') }; this.state.crews[crew.id] = crew; this.save(); return crew; } const crew = { id: id('crew'), leaderId: accountId, members: [accountId], ready: {}, combatImmune: false, joinPolicy: 'open' }; this.state.crews[crew.id] = crew; this.save(); return crew; }
  joinCrew(crewId, accountId, inviteToken) { this.account(accountId); const crew = this.state.crews[crewId]; if (!crew) throw new Error('crew not found'); if (crew.joinPolicy === 'invite-only' && inviteToken !== crew.inviteToken) throw new Error('this crew is invite-only'); if (!crew.members.includes(accountId) && crew.members.length >= this.config.lobby.maxCrewSize) throw new Error('crew is full'); if (!crew.members.includes(accountId)) crew.members.push(accountId); this.save(); return crew; }
  inviteToCrew(crewId, leaderId) { const crew = this.state.crews[crewId]; if (!crew || crew.leaderId !== leaderId) throw new Error('only the crew leader may invite'); return { crewId, inviteToken: crew.inviteToken || id('invite') }; }
  reserve(crewId, region) { const crew = this.state.crews[crewId]; if (!crew) throw new Error('crew not found'); const active = Object.values(this.state.reservations).filter(r => r.status === 'active' && r.region === region); const used = active.reduce((n, r) => n + r.playerCount, 0); if (used + crew.members.length > this.config.lobby.maxPlayers) throw new Error('lobby capacity reached'); const reservation = { id: id('res'), crewId, region, playerCount: crew.members.length, status: 'active', expiresAt: new Date(Date.now() + 5 * 60_000).toISOString() }; this.state.reservations[reservation.id] = reservation; this.save(); return reservation; }
  bindSession(reservationId, accountId) { const r = this.state.reservations[reservationId]; if (!r || r.status !== 'active') throw new Error('reservation unavailable'); const crew = this.state.crews[r.crewId]; if (!crew.members.includes(accountId)) throw new Error('account is not in crew'); const token = crypto.randomBytes(32).toString('base64url'); const session = { id: id('ses'), reservationId, accountId, token, expiresAt: new Date(Date.now() + 15 * 60_000).toISOString() }; this.state.sessions[session.id] = session; this.save(); return session; }
  authenticate(token) { const session = Object.values(this.state.sessions).find(s => s.token === token && Date.parse(s.expiresAt) > Date.now()); if (!session) throw new Error('invalid or expired session'); return session; }
  spawnStarterVehicle(crewId, accountId) { const crew = this.state.crews[crewId]; if (!crew || crew.leaderId !== accountId) throw new Error('only the crew leader may spawn the vehicle'); const existing = Object.values(this.state.vehicles).find(v => v.crewId === crewId && v.status === 'stored'); if (existing) return existing; const vehicle = { id: id('veh'), assetId: this.config.world.vehicle.starterId, crewId, seats: this.config.world.vehicle.seats, occupants: [], condition: this.config.world.vehicle.conditionMax, destination: 'crew_garage', status: 'stored' }; this.state.vehicles[vehicle.id] = vehicle; this.save(); return vehicle; }
  boardVehicle(vehicleId, accountId) { const v = this.state.vehicles[vehicleId]; if (!v) throw new Error('vehicle not found'); const crew = this.state.crews[v.crewId]; if (!crew.members.includes(accountId)) throw new Error('account is not in crew'); if (v.occupants.includes(accountId)) return v; if (v.occupants.length >= v.seats) throw new Error('vehicle is full'); v.occupants.push(accountId); v.status = 'active'; this.save(); return v; }
  updateWorldPosition(accountId, destination) { const valid = this.config.world.destinations.some(d => d.id === destination && d.playable); if (!valid) throw new Error('destination is not playable'); const a = this.account(accountId); a.lastSafeDestination = destination; this.save(); return { accountId, destination }; }
  reconnectPosition(accountId) { const a = this.account(accountId); const valid = this.config.world.destinations.some(d => d.id === a.lastSafeDestination && d.playable); return valid ? a.lastSafeDestination : this.config.world.safeRecovery; }
  restaurantCatalog() { return this.restaurants; }
  reserveRestaurantTable(restaurantId, tableId, crewId, seats) { const restaurant = this.restaurants.restaurants[restaurantId]; if (!restaurant || !restaurant.tables[tableId]) throw new Error('table not found'); if (seats > restaurant.tables[tableId]) throw new Error('table does not have enough seats'); const key = `${restaurantId}:${tableId}`; const current = this.state.restaurantTables[key]; if (current && current.status === 'reserved') throw new Error('table is already reserved'); const reservation = { id: id('table'), restaurantId, tableId, crewId, seats, status: 'reserved', createdAt: new Date().toISOString() }; this.state.restaurantTables[key] = reservation; this.save(); return reservation; }
  createRestaurantOrder(input) { const restaurant = this.restaurants.restaurants[input.restaurantId]; if (!restaurant) throw new Error('restaurant not found'); if (!input.orderKey || !input.playerId || !input.tableId || !Array.isArray(input.items) || !input.items.length) throw new Error('order requires an idempotency key, player, table, and items'); const existing = Object.values(this.state.restaurantOrders).find(o => o.orderKey === input.orderKey); if (existing) return existing; const table = this.state.restaurantTables[`${input.restaurantId}:${input.tableId}`]; if (!table || table.status !== 'reserved' || table.crewId !== input.crewId) throw new Error('table is not reserved for this crew'); const menu = new Map(restaurant.items.map(([name, price, category]) => [name, { name, price, category }])); const lines = input.items.map(line => { const item = menu.get(line.name); const quantity = Number(line.quantity || 1); if (!item || !Number.isInteger(quantity) || quantity < 1 || quantity > 20) throw new Error('invalid menu item or quantity'); return { ...item, quantity }; }); const total = lines.reduce((sum, line) => sum + line.price * line.quantity, 0); const account = this.account(input.playerId); if (account.credits < total) throw new Error('insufficient Casino Credits'); account.credits -= total; account.reservedCredits += total; const order = { id: id('order'), orderKey: input.orderKey, restaurantId: input.restaurantId, menuVersion: restaurant.menuVersion, tableId: input.tableId, crewId: input.crewId, playerId: input.playerId, lines, total, status: 'accepted', reservedAt: new Date().toISOString(), settledAt: null }; this.state.restaurantOrders[order.id] = order; this.save(); return order; }
  transitionRestaurantOrder(orderId, nextStatus) { const order = this.state.restaurantOrders[orderId]; if (!order) throw new Error('order not found'); const allowed = { accepted: ['preparing', 'cancelled'], preparing: ['plated', 'cancelled'], plated: ['served'], served: ['eaten'], eaten: ['cleared'] }; if (!(allowed[order.status] || []).includes(nextStatus)) throw new Error(`invalid order transition ${order.status} -> ${nextStatus}`); const account = this.account(order.playerId); if (nextStatus === 'cancelled') { account.reservedCredits -= order.total; account.credits += order.total; order.refundedAt = new Date().toISOString(); } if (nextStatus === 'served') { account.reservedCredits -= order.total; order.settledAt = new Date().toISOString(); } order.status = nextStatus; this.save(); return order; }
}
module.exports = { Store };
