const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');

const state = globalThis.__bhcState || (globalThis.__bhcState = { crews: new Map(), vehicles: new Map(), accounts: new Map(), tables: new Map(), orders: new Map() });
const owner = { crewId: 'crew_4e5c775890ba', ownerAccountId: 'Big Head Developer', combatImmune: true, joinPolicy: 'invite-only' };
const restaurant = { id: 'BHC_REST_63RD_CHOPHOUSE', name: '63RD STREET CHOPHOUSE', menuVersion: '63RD_CHOPHOUSE_v1', tables: { Table_01: 2, Table_02: 2, Table_03: 4, Table_04: 4 }, items: [['Loaded Potato Skins', 15], ['Crispy Onion Rings', 12], ['63rd Street Sirloin', 65], ['Chophouse Ribeye', 85], ['Steakhouse Burger', 38], ['Smoky Vegetable Skillet', 34], ['Mac and Cheese', 12], ['Garlic Mashed Potatoes', 11], ['Brownie Sundae', 17], ['Apple Crumble', 16], ['House Lemonade', 7], ['Cola', 6]] };
const destinations = [
  ['arrival_plaza', 'Arrival Plaza', true], ['casino_strip', 'Casino Strip', true],
  ['grand_casino', 'The Grand Casino', true], ['equipment_shop', 'Equipment Shop', true],
  ['crew_garage', 'Crew Garage', true], ['service_district', 'Service District', true],
  ['rooftop_overlook', 'Rooftop Overlook', true]
];
const id = p => `${p}_${crypto.randomBytes(6).toString('hex')}`;
const send = (res, status, value, type = 'application/json') => { res.statusCode = status; res.setHeader('content-type', type); res.setHeader('cache-control', 'no-store'); res.end(type === 'application/json' ? JSON.stringify(value) : value); };
const readBody = req => new Promise((resolve, reject) => { let text = ''; req.on('data', c => { text += c; if (text.length > 100000) reject(new Error('body too large')); }); req.on('end', () => { try { resolve(text ? JSON.parse(text) : {}); } catch { reject(new Error('invalid JSON')); } }); });

module.exports = async (req, res) => {
  try {
    const route = req.query?.route ? `/api/${req.query.route}` : req.url.split('?')[0];
    if (req.method === 'GET' && route === '/api/restaurants') return send(res, 200, { version: 'restaurants_v1', restaurants: { [restaurant.id]: restaurant } });
    if (req.method === 'GET') return send(res, 200, { lobby: { maxPlayers: 100, maxCrewSize: 4 }, ownerCrew: owner, vehicle: { assetId: 'BHC_VEH_CREW_VAN', seats: 4 }, destinations: destinations.map(([id, name, playable]) => ({ id, name, playable })) });
    if (req.method !== 'POST') return send(res, 404, { error: 'not found' });
    const body = await readBody(req);
    if (route === '/api/restaurants/table/reserve') { if (!restaurant.tables[body.tableId]) throw Error('table not found'); const key = `${restaurant.id}:${body.tableId}`; if (state.tables.has(key)) throw Error('table is already reserved'); const table = { id: id('table'), restaurantId: restaurant.id, tableId: body.tableId, crewId: body.crewId, seats: body.seats || restaurant.tables[body.tableId] }; if (table.seats > restaurant.tables[body.tableId]) throw Error('table does not have enough seats'); state.tables.set(key, table); return send(res, 201, table); }
    if (route === '/api/restaurants/orders') { if (state.orders.has(body.orderKey)) return send(res, 200, state.orders.get(body.orderKey)); const table = state.tables.get(`${restaurant.id}:${body.tableId}`); if (!table || table.crewId !== body.crewId) throw Error('table is not reserved for this crew'); const prices = new Map(restaurant.items); const lines = body.items.map(item => { const price = prices.get(item.name); if (!price) throw Error('invalid menu item'); return { name: item.name, price, quantity: item.quantity || 1 }; }); const total = lines.reduce((n, line) => n + line.price * line.quantity, 0); const account = state.accounts.get(body.playerId) || { id: body.playerId, credits: 500, reservedCredits: 0 }; if (account.credits < total) throw Error('insufficient Casino Credits'); account.credits -= total; account.reservedCredits += total; state.accounts.set(body.playerId, account); const order = { id: id('order'), orderKey: body.orderKey, restaurantId: restaurant.id, menuVersion: restaurant.menuVersion, tableId: body.tableId, crewId: body.crewId, playerId: body.playerId, lines, total, status: 'accepted' }; state.orders.set(body.orderKey, order); return send(res, 201, order); }
    if (route === '/api/restaurants/orders/transition') { const order = [...state.orders.values()].find(value => value.id === body.orderId); if (!order) throw Error('order not found'); const allowed = { accepted: ['preparing', 'cancelled'], preparing: ['plated', 'cancelled'], plated: ['served'], served: ['eaten'], eaten: ['cleared'] }; if (!(allowed[order.status] || []).includes(body.status)) throw Error(`invalid order transition ${order.status} -> ${body.status}`); const account = state.accounts.get(order.playerId); if (body.status === 'cancelled') { account.reservedCredits -= order.total; account.credits += order.total; } if (body.status === 'served') account.reservedCredits -= order.total; order.status = body.status; return send(res, 200, order); }
    if (route === '/api/crews') { if (!body.accountId) throw Error('accountId is required'); if (body.accountId === owner.ownerAccountId) { const existing = state.crews.get(owner.crewId); if (existing) return send(res, 200, existing); const crew = { id: owner.crewId, leaderId: owner.ownerAccountId, members: [owner.ownerAccountId], combatImmune: true, joinPolicy: 'invite-only', inviteToken: id('invite') }; state.crews.set(crew.id, crew); return send(res, 201, crew); } const crew = { id: id('crew'), leaderId: body.accountId, members: [body.accountId], combatImmune: false, joinPolicy: 'open' }; state.crews.set(crew.id, crew); return send(res, 201, crew); }
    if (route === '/api/crews/join') { const crew = state.crews.get(body.crewId); if (!crew) throw Error('crew not found'); if (crew.joinPolicy === 'invite-only' && body.inviteToken !== crew.inviteToken) throw Error('this crew is invite-only'); if (!crew.members.includes(body.accountId) && crew.members.length >= 4) throw Error('crew is full'); if (!crew.members.includes(body.accountId)) crew.members.push(body.accountId); return send(res, 200, crew); }
    if (route === '/api/crews/invite') { const crew = state.crews.get(body.crewId); if (!crew || crew.leaderId !== body.accountId) throw Error('only the crew leader may invite'); return send(res, 200, { crewId: crew.id, inviteToken: crew.inviteToken }); }
    if (route === '/api/world/vehicle') { const crew = state.crews.get(body.crewId); if (!crew || crew.leaderId !== body.accountId) throw Error('only the crew leader may spawn the vehicle'); const vehicle = { id: id('veh'), crewId: body.crewId, assetId: 'BHC_VEH_CREW_VAN', seats: 4, occupants: [], condition: 100, destination: 'crew_garage' }; state.vehicles.set(vehicle.id, vehicle); return send(res, 201, vehicle); }
    if (route === '/api/world/vehicle/board') { const vehicle = state.vehicles.get(body.vehicleId); if (!vehicle) throw Error('vehicle not found'); const crew = state.crews.get(vehicle.crewId); if (!crew.members.includes(body.accountId)) throw Error('account is not in crew'); if (vehicle.occupants.length >= vehicle.seats && !vehicle.occupants.includes(body.accountId)) throw Error('vehicle is full'); if (!vehicle.occupants.includes(body.accountId)) vehicle.occupants.push(body.accountId); return send(res, 200, vehicle); }
    if (route === '/api/world/position') { if (!destinations.some(d => d[0] === body.destination && d[2])) throw Error('destination is not playable'); return send(res, 200, { accountId: body.accountId, destination: body.destination }); }
    return send(res, 404, { error: 'not found' });
  } catch (error) { return send(res, 400, { error: error.message }); }
};
